vich_uploader:
  db_driver: orm

  mappings:
    game_image:
      uri_prefix: /uploads/games
      upload_destination: '%kernel.project_dir%/public/uploads/games'
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer